language: c
env:
  - OCAML_VERSION=4.03.0
  - OCAML_VERSION=4.04.0
  - OCAML_VERSION=4.05.0
  - OCAML_VERSION=4.06.0
addons:
  apt:
    sources:
      - avsm
    packages:
      - opam
      - time
cache:
  directories:
    - $HOME/.opam
before_install:
  - echo "Installing a decent version of GNU make."
  - wget http://ftp.gnu.org/gnu/make/make-4.1.tar.gz
  - tar xf make-4.1.tar.gz
  - cd make-4.1
  - ./configure
  - make
  - mkdir make_bin
  - cp make make_bin
  - cd ..
  - export PATH="`pwd`/make-4.1/make_bin:$PATH"
  - echo "Should now have GNU make 4.1."
  - export OPAMYES=1
  - export OPAMVERBOSE=1
  - opam init
  - opam switch ${OCAML_VERSION}
  - eval `opam config env`
  - opam install ocamlbuild ocamlfind
  - opam install earley.1.0.2 earley-ocaml.1.0.2
  - opam install camlzip imagelib sqlite3
  - make configure
  - ./configure
  - make
  - make packages
install:
  - make install
script:
  - cd patobook
  - make
  - echo "OK"
os:
  - linux
notifications:
  email:
    - rodolphe.lepigre@inria.fr
